apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: APP_IMAGE
    newName: APP_IMAGE
    newTag: placeholder       # `kustomize edit set image APP_IMAGE=<real-ref>` in CI overwrites both
